### ISSUE TITLE
Highlighting when there is no JS enabled?

### ISSUE THREAD

**Issue by beseven** [nhsuk/gp-finder#106]
Currently, we are using mark.js for the highlighting. 

Considerations for non-js based highlighting: https://github.com/nhsuk/gp-finder/pull/92/files/2c946d6cb05c6466430ac3e7fedef0eb79035910#diff-c66b38acba6eb7efc99cc3289cf6f1e5 (#92)

**Comment by neilbmclaughlin** [comment]
Captured here: https://trello.com/c/hdbHVnTX/603-feature-highlighting-of-search-terms-in-gp-lookup-search-results
