### ISSUE TITLE
Make sure DB connection is ready before running tests

### ISSUE THREAD

**Issue by beseven** [nhsuk/gp-finder#107]
The tests sometimes fail locally the first time around as the DB connection might not be available at that point.

The solution for Redis for consideration:
https://github.com/mochajs/mocha/issues/268
https://github.com/perki/readyness

**Comment by st3v3nhunt** [comment]
Simple bash script e.g. https://raw.githubusercontent.com/nhsuk/gp-finder/5ac65d141052743fff2ca2943c60b1e306588298/scripts/utils

**Comment by st3v3nhunt** [comment]
Redundant now Elasticsearch is being used.
