### ISSUE TITLE
Remove non-minified JS assets

### ISSUE THREAD

**Issue by st3v3nhunt** [nhsuk/gp-finder#125]
Neither `mark.js` or `details.polyfill.js` are minified. They should be. However, rather than just minify them it might make more sense to use a CDN. Solution depends on discussion with the wider team.

**Comment by neilbmclaughlin** [comment]
@ajthomascouk - is this fixed. If so can you close it.

**Comment by ajthomascouk** [comment]
yeah both minified [`mark.js`](https://beta.nhs.uk/book-a-gp-appointment/js/vendor/highlight/jquery.mark-8.10.1.min.js)

**Comment by ajthomascouk** [comment]
Yeah both minified: 
[`query.mark-8.10.1.min.js`](https://beta.nhs.uk/book-a-gp-appointment/js/vendor/highlight/jquery.mark-8.10.1.min.js)
[`details.polyfill-1.0.0.min.js`](https://beta.nhs.uk/book-a-gp-appointment/js/vendor/polyfills/details.polyfill-1.0.0.min.js)

Also added version numbers into the filename.
