### ISSUE TITLE
Non English outcodes should be handled on search and shouldn't be filtered

### ISSUE THREAD

**Issue by beseven** [nhsuk/gp-finder#146]
@neilbmclaughlin has raised this issue with Postcodes IO https://github.com/ideal-postcodes/postcodes.io/issues/120 and is looking to implement a fix to the `outcode` method that would return the country/countries of the outcode in an Array.

Until then we are sticking with the Regex filtering, to be removed when the solution above is in place.

**Comment by neilbmclaughlin** [comment]
Resolved by https://github.com/nhsuk/gp-finder/pull/164.
