### ISSUE TITLE
Upgrade packages prior to push to the github repo

### ISSUE THREAD

**Issue by neilbmclaughlin** [nhsuk/gp-finder#183]
make `yarn upgrade-interactive` part of the _prepush_ githook.

**Comment by beseven** [comment]
Is this conflicting with our discussion about upgrading as a separate PR @neilbmclaughlin ?

**Comment by st3v3nhunt** [comment]
Closing this issue as packages are updated as and when required with the changes be recorded within `yarn.lock` and sometimes in `package.json`.
